#!/usr/bin/env bash
# configuring web-02 to be identical to web-01

sudo apt update
sudo apt install nginx -y
sudo service nginx start
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
echo "Hello World!" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart
